/**
 * @fileoverview Mock data for development
 * @version 1.0.0
 */

import type { Product } from '@/types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Диван "Комфорт"',
    description: 'Современный диван с мягкой обивкой и эргономичной спинкой',
    price: 89900,
    oldPrice: 109900,
    category: 'sofas',
    images: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800'],
    materials: ['Велюр', 'Массив дуба'],
    dimensions: { width: 220, height: 85, depth: 95, unit: 'cm' },
    customizable: true,
    inStock: true,
    rating: 4.8,
    reviewsCount: 47,
  },
  {
    id: '2',
    name: 'Кресло "Лофт"',
    description: 'Стильное кресло в индустриальном стиле',
    price: 34900,
    category: 'chairs',
    images: ['https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800'],
    materials: ['Кожа', 'Металл'],
    dimensions: { width: 75, height: 95, depth: 80, unit: 'cm' },
    customizable: true,
    inStock: true,
    rating: 4.9,
    reviewsCount: 32,
  },
  {
    id: '3',
    name: 'Стол обеденный "Скандинавия"',
    description: 'Минималистичный обеденный стол из массива',
    price: 54900,
    oldPrice: 64900,
    category: 'tables',
    images: ['https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800'],
    materials: ['Массив сосны', 'Масло-воск'],
    dimensions: { width: 180, height: 75, depth: 90, unit: 'cm' },
    customizable: true,
    inStock: false,
    rating: 4.7,
    reviewsCount: 28,
  },
  {
    id: '4',
    name: 'Кровать "Империя"',
    description: 'Роскошная кровать с мягким изголовьем',
    price: 124900,
    category: 'beds',
    images: ['https://images.unsplash.com/photo-1505693314120-0d443867891c?w=800'],
    materials: ['Бархат', 'Массив березы'],
    dimensions: { width: 200, height: 120, depth: 220, unit: 'cm' },
    customizable: true,
    inStock: true,
    rating: 5.0,
    reviewsCount: 15,
  },
  {
    id: '5',
    name: 'Шкаф-купе "Модерн"',
    description: 'Вместительный шкаф с зеркальными дверями',
    price: 79900,
    category: 'wardrobes',
    images: ['https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800'],
    materials: ['ЛДСП', 'Зеркало'],
    dimensions: { width: 240, height: 240, depth: 60, unit: 'cm' },
    customizable: true,
    inStock: true,
    rating: 4.6,
    reviewsCount: 41,
  },
  {
    id: '6',
    name: 'Кухня "Классика"',
    description: 'Кухонный гарнитур из массива с патиной',
    price: 324900,
    oldPrice: 389900,
    category: 'kitchen',
    images: ['https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800'],
    materials: ['Массив ясеня', 'Мрамор'],
    dimensions: { width: 360, height: 240, depth: 60, unit: 'cm' },
    customizable: true,
    inStock: false,
    rating: 4.9,
    reviewsCount: 23,
  },
];
